# Generated by Django 3.2.6 on 2021-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contributors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributors',
        ),
    ]
