# Generated by Django 3.2.6 on 2021-09-10 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('fa', 'Faible'), ('mo', 'Moyenne'), ('el', 'Elevée')], max_length=2),
        ),
        migrations.AlterField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('af', 'A faire'), ('ec', 'En cours'), ('te', 'Terminé')], max_length=2),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('bu', 'Bug'), ('am', 'Amélioration'), ('ta', 'Tâche')], max_length=2),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('be', 'Back-end'), ('fe', 'Front-end'), ('ios', 'iOS'), ('and', 'Android')], max_length=3),
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('cere', 'Create/Read'), ('upde', 'Update/Delete')], max_length=4)),
                ('role', models.CharField(choices=[('auth', 'Author'), ('cont', 'Contributor')], max_length=4)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
