# Generated by Django 3.2.6 on 2021-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210910_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(blank=True, choices=[('cere', 'Create/Read'), ('upde', 'Update/Delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(blank=True, choices=[('auth', 'Author'), ('cont', 'Contributor')], max_length=4),
        ),
    ]
