# Generated by Django 3.2.6 on 2021-09-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_issues_assignee_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='assignee_user_id',
        ),
        migrations.AddField(
            model_name='issues',
            name='assignee_user_id',
            field=models.ManyToManyField(blank=True, related_name='assignee', to='projects.Contributors'),
        ),
    ]
