# Generated by Django 3.2.6 on 2021-09-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210930_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='issue_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.issues'),
        ),
    ]
