# Generated by Django 3.2.6 on 2021-10-08 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projects_author_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='assignee_user_id',
        ),
        migrations.AddField(
            model_name='issues',
            name='assignee_user_id',
            field=models.ForeignKey(blank=True, default=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='projects.contributors'),
        ),
    ]
