# Generated by Django 3.2.6 on 2021-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211008_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='assignee_user_id',
        ),
        migrations.AddField(
            model_name='issues',
            name='assignee_user_id',
            field=models.ManyToManyField(blank=True, related_name='assignee', to='projects.Contributors'),
        ),
    ]
