# Generated by Django 3.2.6 on 2021-10-08 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20211008_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='assignee_user_id',
            field=models.ManyToManyField(blank=True, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
